const Apptheme = {
    token: {
        textColor: '#000',
        colorPrimary: '#003594',
        colorPrimaryBg: '#e6f7ff',
        colorBgBase: '#fff',
        colorBgMask: 'rgba(0, 0, 0, 0.45)',
        fontSizeBase: '14px',
        fontSizeLg: '16px',
        fontSizeSm: '12px',
        fontSizeXs: '10px',
        fontSizeXxs: '8px',
        colorTextBase: '#333',
        colorTextSecondary: '#666',
        colorTextPlaceholder: '#999',
        colorTextDisabled: '#ccc',
        colorTextError: '#f5222d',
        colorTextWarning: '#faad14',
        colorTextSuccess: '#52c41a',
        colorTextInfo: '#1890ff',
        colorTextLink: '#1890ff',
        colorTextLinkHover: '#40a9ff',
        colorTextLinkActive: '#096dd9',
        colorTextLinkFocus: '#40a9ff',
        colorTextLinkVisited: '#1890ff',
        colorTextLinkDisabled: '#ccc',
        colorError: '#f5222d',
        colorWarning: '#faad14',
        colorSuccess: '#52c41a',
        colorInfo: '#1890ff',
        colorBgError: '#fff1f0',
        colorBgWarning: '#fffbe6',
        colorBgSuccess: '#f6ffed',
        colorBgInfo: '#e6f7ff',
        colorBgLink: '#e6f7ff',
        colorBgLinkHover: '#bae7ff',
        colorBgLinkActive: '#91d5ff',
        colorBgLinkFocus: '#bae7ff',
        colorBgLinkVisited: '#e6f7ff',
        colorBgLinkDisabled: '#f5f5f5',
        colorBgDisabled: '#f5f5f5',
        colorBgActive: '#e6f7ff',
        colorBgFocus: '#bae7ff',
        colorBgHover: '#e6f7ff',
        colorBgSelected: '#e6f7ff',
        colorBgSelectedHover: '#bae7ff',
        colorBgSelectedActive: '#91d5ff',
        colorBgSelectedFocus: '#bae7ff',
        colorBgSelectedDisabled: '#f5f5f5',
        colorBgSelectedText: '#333',
        colorBgSelectedTextHover: '#333',
        colorBgSelectedTextActive: '#333',
        colorBgSelectedTextFocus: '#333',
        colorBgSelectedTextDisabled: '#ccc',
        colorBgSelectedIcon: '#333',
        colorBgSelectedIconHover: '#333',
        colorBgSelectedIconActive: '#333',
        colorBgSelectedIconFocus: '#333',
        colorBgSelectedIconDisabled: '#ccc',
        colorBgSelectedLink: '#e6f7ff',
        colorBgSelectedLinkHover: '#bae7ff',
        colorBgSelectedLinkActive: '#91d5ff',
        colorBgSelectedLinkFocus: '#bae7ff',
        colorBgSelectedLinkDisabled: '#f5f5f5',
        colorBgSelectedLinkText: '#333',
        colorBgSelectedLinkTextHover: '#333',
        colorBgSelectedLinkTextActive: '#333',
        colorBgSelectedLinkTextFocus: '#333',
        colorBgSelectedLinkTextDisabled: '#ccc',
        colorBgSelectedLinkIcon: '#333',
        colorBgSelectedLinkIconHover: '#333',
        colorBgSelectedLinkIconActive: '#333',
        colorBgSelectedLinkIconFocus: '#333',


    },
}

export default Apptheme